"""VOALearningEnglishProvider: the standard slow-English source.

VOA Learning English is a US federal government (public-domain) source; its
episodes are slow and clearly articulated (~110 wpm Special English), which
matches the initial difficulty band. The podcast RSS exposes direct MP3 URLs
and titles. The official transcript is loaded by client-side JS and is not
available server-side (verified across desktop/mobile/AMP), so the transcript
is produced by a higher-accuracy local ASR pass (whisper small) and marked as
ASR-generated; its segment timestamps are inherently aligned, which keeps the
dictation timeline precise.
"""

from __future__ import annotations

import re
import subprocess
import urllib.request
from dataclasses import dataclass, field
from pathlib import Path

from app.adapters.speech import SpeechRecognitionProvider, WhisperASRProvider
from app.adapters.web_material import (
    MaterialSource,
    WebMaterialProvider,
    align_sentences,
    split_sentences,
)

#: Slow-English program zones (Words and Their Stories, Everyday Grammar,
#: Let's Learn English, American Stories ...).
SLOW_ZONES = [4456, 4791, 5254, 5535, 1581]

_USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) LanguageTrainingAgent P0"


def _fetch(url: str) -> str:
    request = urllib.request.Request(url, headers={"User-Agent": _USER_AGENT})
    with urllib.request.urlopen(request, timeout=30) as response:
        return response.read().decode("utf-8", "ignore")


def _wav_duration(wav_path: Path) -> float:
    import wave

    with wave.open(str(wav_path), "rb") as wav_file:
        return wav_file.getnframes() / wav_file.getframerate()


def _parse_itunes_duration(value: str) -> float | None:
    """HH:MM:SS / MM:SS / SS -> seconds; None when unparseable."""
    value = value.strip()
    if not value:
        return None
    parts = value.split(":")
    try:
        numbers = [int(part) for part in parts]
    except ValueError:
        return None
    if not 1 <= len(numbers) <= 3:
        return None
    seconds = 0
    for number in numbers:
        seconds = seconds * 60 + number
    return float(seconds)


class VOALearningEnglishProvider:
    """Public-domain slow English; transcript generated by local ASR."""

    def __init__(self, zone_ids: list[int] | None = None, asr: SpeechRecognitionProvider | None = None) -> None:
        self.zone_ids = zone_ids or SLOW_ZONES
        # VOA audio is slow and clear; a higher-accuracy model keeps the
        # ASR-generated transcript usable as the standard answer.
        self.asr = asr or WhisperASRProvider(model_size="small")

    def _list_episodes(self, zone_ids: list[int] | None = None) -> list[tuple[str, str, str, float | None]]:
        """(article_url, mp3_url, title, duration_seconds) per RSS item; the
        duration comes from the itunes:duration field when present."""
        episodes: list[tuple[str, str, str, float | None]] = []
        for zone_id in zone_ids or self.zone_ids:
            try:
                xml = _fetch(f"https://learningenglish.voanews.com/podcast/?count=10&zoneId={zone_id}")
            except Exception:
                continue
            for item in re.findall(r"<item>([\s\S]*?)</item>", xml):
                link = re.search(r"<link>(.*?)</link>", item)
                mp3 = re.search(r'<enclosure[^>]*url="([^"]+)"', item)
                title = re.search(r"<title>(.*?)</title>", item)
                duration = re.search(r"<itunes:duration>(.*?)</itunes:duration>", item)
                if link and mp3:
                    clean_title = re.sub(r"<[^>]+>", "", title.group(1)).strip() if title else link.group(1)
                    episodes.append(
                        (
                            link.group(1).strip(),
                            mp3.group(1).strip(),
                            clean_title,
                            _parse_itunes_duration(duration.group(1)) if duration else None,
                        )
                    )
        return episodes

    def download_audio(self, mp3_url: str, audio_id: str, work_dir: Path) -> Path:
        """Download and transcode to 16 kHz mono WAV; returns the wav path."""
        work_dir.mkdir(parents=True, exist_ok=True)
        mp3_path = work_dir / f"{audio_id}.mp3"
        wav_path = work_dir / f"{audio_id}.wav"
        if not mp3_path.exists():
            urllib.request.urlretrieve(mp3_url, mp3_path)
        if not wav_path.exists():
            subprocess.run(
                ["ffmpeg", "-y", "-loglevel", "error", "-i", str(mp3_path),
                 "-ac", "1", "-ar", "16000", "-sample_fmt", "s16", str(wav_path)],
                check=True,
            )
        return wav_path

    def search_next(
        self,
        *,
        exclude_urls: set[str],
        work_dir: Path,
        asr: SpeechRecognitionProvider | None = None,
        criteria: object | None = None,
    ) -> MaterialSource:
        episodes = [ep for ep in self._list_episodes() if ep[0] not in exclude_urls]
        if not episodes:
            raise ValueError("No unseen VOA Learning English episodes available")
        article_url, mp3_url, title = episodes[0]
        article_id = re.search(r"/(\d+)\.html$", article_url).group(1)
        material_id = f"web-voa-{article_id}"

        work_dir.mkdir(parents=True, exist_ok=True)
        mp3_path = work_dir / f"{material_id}.mp3"
        wav_path = work_dir / f"{material_id}.wav"
        if not mp3_path.exists():
            urllib.request.urlretrieve(mp3_url, mp3_path)
        if not wav_path.exists():
            subprocess.run(
                ["ffmpeg", "-y", "-loglevel", "error", "-i", str(mp3_path),
                 "-ac", "1", "-ar", "16000", "-sample_fmt", "s16", str(wav_path)],
                check=True,
            )

        segments = self.asr.transcribe(str(wav_path))
        transcript = " ".join(segment.text for segment in segments)
        sentences = split_sentences(transcript)
        aligned = align_sentences(sentences, segments)

        return MaterialSource(
            material_id=material_id,
            title=f"VOA Learning English - {title}",
            audio_path=str(wav_path),
            transcript=transcript,
            source_url=article_url,
            source_name="VOA Learning English (slow; transcript from local ASR)",
            duration_seconds=_wav_duration(wav_path),
            timestamped_sentences=tuple(aligned),
        )
